# Generated by Django 3.0.6 on 2020-05-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Frontend'), (2, 'UX/UI design'), (3, 'Backend'), (4, 'FullStack'), (5, 'Devops')], default=4),
        ),
    ]
