# Generated by Django 3.0.6 on 2020-05-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200511_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.ManyToManyField(default=1, related_name='status', to='accounts.EmployeeStatus'),
        ),
    ]
