# Generated by Django 3.0.6 on 2020-05-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200511_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'applicant'), (2, 'test candidate'), (3, 'successful candidate'), (4, 'employee')], default=1),
        ),
    ]
