# Generated by Django 3.0.6 on 2020-05-12 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200512_0512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeStatus',
        ),
    ]
